
== Buffer Objects


=== Create and Bind Buffer Objects

[small]#Rfr: https://www.opengl.org/wiki/Category:Core_API_Ref_Buffer_Objects[Buffer Objects].#

[[buffertarget]]
[small]#*buffer target*: '_array_' for GL_ARRAY_BUFFER, '_element array_' for GL_ELEMENT_ARRAY_BUFFER, etc.#

[[gl.gen_buffers]]
* _buffer1_, _buffer2_, _..._ = *gen_buffers*([_n_ = 1])

[[gl.create_buffers]]
* *create_buffers*(_buffer1_ [, _buffer2_, _..._])

[[gl.delete_buffers]]
* *delete_buffers*(_buffer1_ [, _buffer2_, _..._])

[[gl.bind_buffer]]
* *bind_buffer*(<<buffertarget,_target_>> [, _buffer_]) +
*unbind_buffer*(<<buffertarget,_target_>>) _NONGL_

[[gl.new_buffer]]
* _buffer_ = *new_buffer*(<<buffertarget,_target_>>) _NONGL_ +
[small]#Gen & bind one buffer.#
[small]#See <<snippet_rectangle, example>>.#

=== Create/Modify Buffer Object Data

[[gl.buffer_storage]]
* _size_ = *buffer_storage*(<<buffertarget,_target_>>|_buffer_, <<data,_data_>> [, _flag_, _flag_, _..._]) +
[small]#_flag_: '_dynamic range_' for GL_DYNAMIC_RANGE_BIT, '_map read_' for GL_MAP_READ_BIT, etc. +
Rfr: https://www.opengl.org/wiki/GLAPI/glBufferStorage[glBufferStorage].#

[[gl.buffer_data]]
* _size_ = *buffer_data*(<<buffertarget,_target_>>|_buffer_, <<data,_data_>>|_size_, _usage_) +
[small]#_size_: size of memory to allocate for the buffer (in bytes). +
_usage_: '_static draw_' for GL_STATIC_DRAW, '_static read_' for GL_STATIC READ, etc. +
Rfr: https://www.opengl.org/wiki/GLAPI/glBufferData[glBufferData].
See <<snippet_rectangle, example>> and <<datahandling, 'Data handling utilities'>>.#

[[gl.buffer_sub_data]]
* _size_ = *buffer_sub_data*(<<buffertarget,_target_>>|_buffer_, _offset_, <<data,_data_>>) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glBufferSubData[glBufferSubData].
See also <<datahandling, 'Data handling utilities'>>.#

[[gl.clear_buffer_data]]
* *clear_buffer_data*(<<buffertarget,_target_>>|_buffer_, <<intformat, _intformat_>>, <<format, _format_>>, <<type, _type_>> [, <<data,_data_>>]) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glClearBufferData[glClearBufferData].
See also <<datahandling, 'Data handling utilities'>>.#

[[gl.clear_buffer_sub_data]]
* *clear_buffer_sub_data*(<<buffertarget,_target_>>|_buffer_, <<intformat, _intformat_>>), _offset_, _size_, <<format, _format_>>, <<type, _type_>> [, <<data,_data_>>]) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glClearBufferSubData[glClearBufferSubData].
See also <<datahandling, 'Data handling utilities'>>.#

[[gl.bind_buffer_range]]
* *bind_buffer_range*(<<buffertarget,_target_>>, _index_, _buffer_, _offset_, _size_) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glBindBufferRange[glBindBufferRange].#

[[gl.bind_buffer_base]]
* *bind_buffer_base*(<<buffertarget,_target_>>, _index_, _buffer_) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glBindBufferBase[glBindBufferBase].#


=== Map/Unmap Buffer Data

[[gl.map_buffer]]
* *map_buffer*(<<buffertarget,_target_>>|_buffer_, _access_) +
*map_buffer_range*(<<buffertarget,_target_>>|_buffer_, _offset_, _length_ [, _accessbit1_, _..._]) +
*unmap_buffer*(<<buffertarget,_target_>>|_buffer_) +
[small]#_access_: 'read only_', '_write only_', '_read write_', +
_accessbit_: '_read_' for GL_MAP_READ_BIT, '_invalidate buffer_' for GL_INVALIDATE_BUFFER_BIT, etc. +
Rfr: https://www.opengl.org/wiki/GLAPI/glMapBuffer[glMapBuffer], 
https://www.opengl.org/wiki/GLAPI/glMapBufferRange[glMapBufferRange].#

[[gl.flush_mapped_buffer_range]]
* *flush_mapped_buffer_range*(<<buffertarget,_target_>>|_buffer_, _offset_, _length_) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glFlushMappedBufferRange[glFlushMappedBufferRange].#

[[gl.mapped_buffer_write]]
* *mapped_buffer_write*(<<buffertarget,_target_>>|_buffer_, _offset_, <<data,_data_>>) +
* <<data,_data_>> = *mapped_buffer_read*(<<buffertarget,_target_>>|_buffer_, _offset_, _length_) +
[small]#Write/read data to/from a mapped buffer (non-OpenGL functions).#

=== Invalidate Buffer Data

[[gl.invalidate_buffer_data]]
* *invalidate_buffer_data*(_buffer_) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glInvalidateBufferData[glInvalidateBufferData].#

[[gl.invalidate_buffer_sub_data]]
* *invalidate_buffer_sub_data*(_buffer_, _offset_, _length_) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glInvalidateBufferSubData[glInvalidateBufferSubData].#

=== Buffer Object Queries

[[gl.is_buffer]]
* _boolean_ = *is_buffer*(_buffer_)


[[gl.get_buffer_sub_data]]
* <<data,_data_>> = *get_buffer_sub_data*(<<buffertarget,_target_>>|_buffer_, _offset_, _size_) +
[small]#Rfr: https://www.opengl.org/wiki/GLAPI/glGetBufferSubData[glGetBufferSubData].#

[[gl.get_buffer_parameter]]
* _value(s)_ = *get_buffer_parameter*(<<buffertarget,_target_>>|_buffer_, _pname_) +
[small]#_pname_: '_size_' for GL_BUFFER_SIZE, '_storage flags_' for GL_BUFFER_STORAGE_FLAGS, etc. +
Rfr: https://www.opengl.org/wiki/GLAPI/glGetBufferParameter[glGetBufferParameter].#

=== Copy Between Buffers

[[gl.copy_buffer_sub_data]]
* *copy_buffer_sub_data*(_readtarget_|_readbuffer_, _writetarget_|_writebuffer_, _readoffset_, _writeoffset_, _size_) +
[small]#Source and destination must be specified both as targets or both as buffer names. +
Rfr: https://www.opengl.org/wiki/GLAPI/glCopyBufferSubData[glCopyBufferSubData].#


