
[[datahandling]]
== Data handling utilities

The functions described in this section are MoonGL-specific utilities (they have no 
equivalent in OpenGL) that can be used to encode data from Lua variables to 
binary strings, and to decode data the other way round.
They are useful to deal with the binary string format expected by GL functions like, 
for example, <<gl.buffer_data, gl.buffer_data>>( ) and 
<<gl.buffer_sub_data, gl.buffer_sub_data>>( ).


[[gl.flatten]]
* *gl.flatten* (_table_) +
-> _val1_, _..._, _valN_ +
[small]#Flattens out the given _table_ and returns the terminal elements in the order they are found.
Similar to Lua's 
link:++http://www.lua.org/manual/5.3/manual.html#pdf-table.unpack++[table.unpack]( ), 
it also unpacks any nested table. Only the array part of the table(s) is considered.#


[[gl.sizeof]]
* *gl.sizeof* (<<type, _type_>>) +
-> size +
[small]#Returns the size, in bytes, of the GL _type_.#


[[gl.pack]]
* *gl.pack* (<<type, _type_>>, _val1_, _..._, _valN_) +
*gl.pack* (<<type, _type_>>, _table_) +
-> _bstring_ +
[small]#Packs the numbers _val1_, _..._, _valN_ in a binary string, encoding them
according to _type_. The values may be passed also in a (possibly nested) table _t_.#


* *gl.unpack* (<<type, _type_>>, _bstring_) +
-> _val1_, _..._, _valN_ +
[small]#Unpacks the binary string _bstring_, interpreting it as a sequence of values
enncoded according to _type_, and returns the extracted values. The length of the
binary string must be a multiple of _gl.sizeof(type)_.#


<<<

